/*
 * Author: WaldoTheWarfighter
 * Registers the standalone Waldos AI Tweaks mission functions.
 * Locality / Authority: Compilation is local; each function documents its own execution authority.
 * Repeat/JIP: CfgFunctions compilation is repeat-safe and available to joining machines.
 * Arguments: None.
 * Return Value: CfgFunctions declaration.
 * Current callers: include from the consuming mission description.ext.
 * Example: #include "WaldosAITweaks\functions.hpp"
 */
class CfgFunctions {
    class Waldo {
        class AI 
        {
            class ConvoyThreat {file = "MissionScripts\AiScripting\convoyThreat.sqf";};
            class ConvoyDismountLocal {file = "MissionScripts\AiScripting\convoyDismountLocal.sqf";};
            class ConvoyHaltServer {file = "MissionScripts\AiScripting\convoyHaltServer.sqf";};
            class ConvoyCrewLocal {file = "MissionScripts\AiScripting\convoyCrewLocal.sqf";};
            class ConvoySync {file = "MissionScripts\AiScripting\convoySync.sqf";};
            class ConvoyReleaseLocal {file = "MissionScripts\AiScripting\convoyReleaseLocal.sqf";};
            class ConvoyTick {file = "MissionScripts\AiScripting\convoyTick.sqf";};
            class ZenConvoyModule {file = "MissionScripts\AiScripting\zenConvoyModule.sqf";};
            class SimpleAiConvoy {
                file =  "MissionScripts\AiScripting\simpleAiConvoy.sqf";
            };
            class AITweak {
                file = "MissionScripts\AiScripting\AISkillAdjustmentSystem.sqf";
            };
            class AIRebalanceInit {
                file = "MissionScripts\AiScripting\aiRebalanceInit.sqf";
            };
            class AIHeadlessAdoptionResultServer {
                file = "MissionScripts\AiScripting\aiHeadlessAdoptionResultServer.sqf";
            };
            class AIGetDiagnostics {
                file = "MissionScripts\AiScripting\aiGetDiagnostics.sqf";
            };
            class AIApplyProfile {
                file = "MissionScripts\AiScripting\aiApplyProfile.sqf";
            };
            class AIRebalanceStop {
                file = "MissionScripts\AiScripting\aiRebalanceStop.sqf";
            };
            class CortexInit {file = "MissionScripts\AiScripting\Cortex\cortexInit.sqf";};
            class CortexStop {file = "MissionScripts\AiScripting\Cortex\cortexStop.sqf";};
            class CortexIsEligible {file = "MissionScripts\AiScripting\Cortex\cortexIsEligible.sqf";};
            class CortexExternalOwner {file = "MissionScripts\AiScripting\Cortex\cortexExternalOwner.sqf";};
            class CortexCivilianReact {file = "MissionScripts\AiScripting\Cortex\cortexCivilianReact.sqf";};
            class CortexCivilianSetup {file = "MissionScripts\AiScripting\Cortex\cortexCivilianSetup.sqf";};
            class CortexIsPaused {file = "MissionScripts\AiScripting\Cortex\cortexIsPaused.sqf";};
            class CortexQueueJob {file = "MissionScripts\AiScripting\Cortex\cortexQueueJob.sqf";};
            class CortexSchedulerTick {file = "MissionScripts\AiScripting\Cortex\cortexSchedulerTick.sqf";};
            class CortexRegroupOnKill {file = "MissionScripts\AiScripting\Cortex\cortexRegroupOnKill.sqf";};
            class CortexRegroupStep {file = "MissionScripts\AiScripting\Cortex\cortexRegroupStep.sqf";};
            class CortexAirborneCheck {file = "MissionScripts\AiScripting\Cortex\cortexAirborneCheck.sqf";};
            class CortexAirborneDropStep {file = "MissionScripts\AiScripting\Cortex\cortexAirborneDropStep.sqf";};
            class CortexAirborneDrop {file = "MissionScripts\AiScripting\Cortex\cortexAirborneDrop.sqf";};
            class CortexParachuteJump {file = "MissionScripts\AiScripting\Cortex\cortexParachuteJump.sqf";};
            class CortexSettingsLocal {file = "MissionScripts\AiScripting\Cortex\cortexSettingsLocal.sqf";};
            class CortexTuning {file = "MissionScripts\AiScripting\Cortex\cortexTuning.sqf";};
            class CortexOrderReason {file = "MissionScripts\AiScripting\Cortex\cortexOrderReason.sqf";};
            class CortexControlOpenLocal {file = "MissionScripts\AiScripting\Cortex\cortexControlOpenLocal.sqf";};
            class CortexControlPageLocal {file = "MissionScripts\AiScripting\Cortex\cortexControlPageLocal.sqf";};
            class CortexTuningSpec {file = "MissionScripts\AiScripting\Cortex\cortexTuningSpec.sqf";};
            class CortexArtilleryRole {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryRole.sqf";};
            class CortexSetArtilleryRole {file = "MissionScripts\AiScripting\Cortex\cortexSetArtilleryRole.sqf";};
            class CortexReleaseFeatureCrew {file = "MissionScripts\AiScripting\Cortex\cortexReleaseFeatureCrew.sqf";};
            class CortexOwnershipLease {file = "MissionScripts\AiScripting\Cortex\cortexOwnershipLease.sqf";};
            class CortexBuildingBackendStart {file = "MissionScripts\AiScripting\Cortex\cortexBuildingBackendStart.sqf";};
            class CortexBuildingBackendRelease {file = "MissionScripts\AiScripting\Cortex\cortexBuildingBackendRelease.sqf";};
            class CortexAntiArmour {file = "MissionScripts\AiScripting\Cortex\cortexAntiArmour.sqf";};
            class CortexCheckpoint {file = "MissionScripts\AiScripting\Cortex\cortexCheckpoint.sqf";};
            class CortexLocality {file = "MissionScripts\AiScripting\Cortex\cortexLocality.sqf";};
            class CortexSetSpotter {file = "MissionScripts\AiScripting\Cortex\cortexSetSpotter.sqf";};
            class CortexSpotterFix {file = "MissionScripts\AiScripting\Cortex\cortexSpotterFix.sqf";};
            class CortexArtilleryObserve {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryObserve.sqf";};
            class CortexArtilleryReport {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryReport.sqf";};
            class CortexArtilleryAim {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryAim.sqf";};
            class CortexArtilleryAmmo {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryAmmo.sqf";};
            class CortexArtilleryMissionStep {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryMissionStep.sqf";};
            class CortexArtilleryShot {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryShot.sqf";};
            class CortexArtilleryScoot {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryScoot.sqf";};
            class CortexClearRelease {file = "MissionScripts\AiScripting\Cortex\cortexClearRelease.sqf";};
            class CortexOrderDispatch {file = "MissionScripts\AiScripting\Cortex\cortexOrderDispatch.sqf";};
            class CortexOrderLocal {file = "MissionScripts\AiScripting\Cortex\cortexOrderLocal.sqf";};
            class CortexOrderResult {file = "MissionScripts\AiScripting\Cortex\cortexOrderResult.sqf";};
            class CortexCounterObserve {file = "MissionScripts\AiScripting\Cortex\cortexCounterObserve.sqf";};
            class CortexArtilleryFired {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryFired.sqf";};
            class CortexArtilleryRejected {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryRejected.sqf";};
            class CortexArtilleryFire {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryFire.sqf";};
            class CortexArtilleryRequest {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryRequest.sqf";};
            class CortexCanTransmit {file = "MissionScripts\AiScripting\Cortex\cortexCanTransmit.sqf";};
            class CortexBuildingDoor {file = "MissionScripts\AiScripting\Cortex\cortexBuildingDoor.sqf";};
            class CortexClearBuilding {file = "MissionScripts\AiScripting\Cortex\cortexClearBuilding.sqf";};
            class CortexReportServer {file = "MissionScripts\AiScripting\Cortex\cortexReportServer.sqf";};
            class CortexReportLocal {file = "MissionScripts\AiScripting\Cortex\cortexReportLocal.sqf";};
            class CortexHearingLocal {file = "MissionScripts\AiScripting\Cortex\cortexHearingLocal.sqf";};
            class CortexContactReport {file = "MissionScripts\AiScripting\Cortex\cortexContactReport.sqf";};
            class CortexCombinedArmsRequest {file = "MissionScripts\AiScripting\Cortex\cortexCombinedArmsRequest.sqf";};
            class CortexCombinedArmsServer {file = "MissionScripts\AiScripting\Cortex\cortexCombinedArmsServer.sqf";};
            class CortexCombinedArmsLocal {file = "MissionScripts\AiScripting\Cortex\cortexCombinedArmsLocal.sqf";};
            class CortexCombinedGroundStep {file = "MissionScripts\AiScripting\Cortex\cortexCombinedGroundStep.sqf";};
            class CortexCooldown {file = "MissionScripts\AiScripting\Cortex\cortexCooldown.sqf";};
            class CortexCounterBattery {file = "MissionScripts\AiScripting\Cortex\cortexCounterBattery.sqf";};
            class CortexAttackRunFlares {file = "MissionScripts\AiScripting\Cortex\cortexAttackRunFlares.sqf";};
            class CortexAirAttackPlan {file = "MissionScripts\AiScripting\Cortex\cortexAirAttackPlan.sqf";};
            class CortexAirAttack {file = "MissionScripts\AiScripting\Cortex\cortexAirAttack.sqf";};
            class CortexAirHandoverRestoreLocal {file = "MissionScripts\AiScripting\Cortex\cortexAirHandoverRestoreLocal.sqf";};
            class CortexAircraftEligible {file = "MissionScripts\AiScripting\Cortex\cortexAircraftEligible.sqf";};
            class CortexDiscover {file = "MissionScripts\AiScripting\Cortex\cortexDiscover.sqf";};
            class CortexFindCover {file = "MissionScripts\AiScripting\Cortex\cortexFindCover.sqf";};
            class CortexFireControl {file = "MissionScripts\AiScripting\Cortex\cortexFireControl.sqf";};
            class CortexFireCountermeasure {file = "MissionScripts\AiScripting\Cortex\cortexFireCountermeasure.sqf";};
            class CortexFlankEnd {file = "MissionScripts\AiScripting\Cortex\cortexFlankEnd.sqf";};
            class CortexFlankStart {file = "MissionScripts\AiScripting\Cortex\cortexFlankStart.sqf";};
            class CortexFlankStep {file = "MissionScripts\AiScripting\Cortex\cortexFlankStep.sqf";};
            class CortexDrillSetStage {file = "MissionScripts\AiScripting\Cortex\cortexDrillSetStage.sqf";};
            class CortexSetPhase {file = "MissionScripts\AiScripting\Cortex\cortexSetPhase.sqf";};
            class CortexGarrison {file = "MissionScripts\AiScripting\Cortex\cortexGarrison.sqf";};
            class CortexGarrisonApplyLocal {file = "MissionScripts\AiScripting\Cortex\cortexGarrisonApplyLocal.sqf";};
            class CortexGarrisonRelease {file = "MissionScripts\AiScripting\Cortex\cortexGarrisonRelease.sqf";};
            class CortexGrenadeCheck {file = "MissionScripts\AiScripting\Cortex\cortexGrenadeCheck.sqf";};
            class CortexGroupMove {file = "MissionScripts\AiScripting\Cortex\cortexGroupMove.sqf";};
            class CortexGroupMoveClear {file = "MissionScripts\AiScripting\Cortex\cortexGroupMoveClear.sqf";};
            class CortexGroupState {file = "MissionScripts\AiScripting\Cortex\cortexGroupState.sqf";};
            class CortexGroupTick {file = "MissionScripts\AiScripting\Cortex\cortexGroupTick.sqf";};
            class CortexKnowledge {file = "MissionScripts\AiScripting\Cortex\cortexKnowledge.sqf";};
            class CortexLineOfFireClear {file = "MissionScripts\AiScripting\Cortex\cortexLineOfFireClear.sqf";};
            class CortexMorale {file = "MissionScripts\AiScripting\Cortex\cortexMorale.sqf";};
            class CortexRegisterRadar {file = "MissionScripts\AiScripting\Cortex\cortexRegisterRadar.sqf";};
            class CortexSupportServer {file = "MissionScripts\AiScripting\Cortex\cortexSupportServer.sqf";};
            class CortexSupportAssaultServer {file = "MissionScripts\AiScripting\Cortex\cortexSupportAssaultServer.sqf";};
            class CortexSupportStep {file = "MissionScripts\AiScripting\Cortex\cortexSupportStep.sqf";};
            class CortexSupportLocal {file = "MissionScripts\AiScripting\Cortex\cortexSupportLocal.sqf";};
            class CortexSupportApply {file = "MissionScripts\AiScripting\Cortex\cortexSupportApply.sqf";};
            class CortexSupportAck {file = "MissionScripts\AiScripting\Cortex\cortexSupportAck.sqf";};
            class CortexSupportMaintain {file = "MissionScripts\AiScripting\Cortex\cortexSupportMaintain.sqf";};
            class CortexSupportCoordinateStep {file = "MissionScripts\AiScripting\Cortex\cortexSupportCoordinateStep.sqf";};
            class CortexSupportBoundStart {file = "MissionScripts\AiScripting\Cortex\cortexSupportBoundStart.sqf";};
            class CortexReinforce {file = "MissionScripts\AiScripting\Cortex\cortexReinforce.sqf";};
            class CortexReleaseGroup {file = "MissionScripts\AiScripting\Cortex\cortexReleaseGroup.sqf";};
            class CortexRestoreCalm {file = "MissionScripts\AiScripting\Cortex\cortexRestoreCalm.sqf";};
            class CortexRetreat {file = "MissionScripts\AiScripting\Cortex\cortexRetreat.sqf";};
            class CortexSurrender {file = "MissionScripts\AiScripting\Cortex\cortexSurrender.sqf";};
            class CortexThrowGrenade {file = "MissionScripts\AiScripting\Cortex\cortexThrowGrenade.sqf";};
            class CortexFeatureEnabled {file = "MissionScripts\AiScripting\Cortex\cortexFeatureEnabled.sqf";};
            class CortexCombatEffective {file = "MissionScripts\AiScripting\Cortex\cortexCombatEffective.sqf";};
            class CortexCapabilities {file = "MissionScripts\AiScripting\Cortex\cortexCapabilities.sqf";};
            class CortexPassengerReady {file = "MissionScripts\AiScripting\Cortex\cortexPassengerReady.sqf";};
            class CortexInfantrySpeed {file = "MissionScripts\AiScripting\Cortex\cortexInfantrySpeed.sqf";};
            class CortexUnitRole {file = "MissionScripts\AiScripting\Cortex\cortexUnitRole.sqf";};
            class CortexOnboardContact {file = "MissionScripts\AiScripting\Cortex\cortexOnboardContact.sqf";};
            class CortexVehicles {file = "MissionScripts\AiScripting\Cortex\cortexVehicles.sqf";};
            class CortexNavalAssault {file = "MissionScripts\AiScripting\Cortex\cortexNavalAssault.sqf";};
            class CortexNavalRelease {file = "MissionScripts\AiScripting\Cortex\cortexNavalRelease.sqf";};
            class CortexTacticalStart {file = "MissionScripts\AiScripting\Cortex\cortexTacticalStart.sqf";};
            class CortexAdvanceStart {file = "MissionScripts\AiScripting\Cortex\cortexAdvanceStart.sqf";};
            class CortexAmmoShare {file = "MissionScripts\AiScripting\Cortex\cortexAmmoShare.sqf";};
            class CortexCoordinatedAssault {file = "MissionScripts\AiScripting\Cortex\cortexCoordinatedAssault.sqf";};
            class CortexDefend {file = "MissionScripts\AiScripting\Cortex\cortexDefend.sqf";};
            class CortexDefendApplyLocal {file = "MissionScripts\AiScripting\Cortex\cortexDefendApplyLocal.sqf";};
            class CortexDefendRelease {file = "MissionScripts\AiScripting\Cortex\cortexDefendRelease.sqf";};
            class CortexDefendStep {file = "MissionScripts\AiScripting\Cortex\cortexDefendStep.sqf";};
            class CortexPlanRoute {file = "MissionScripts\AiScripting\Cortex\cortexPlanRoute.sqf";};
            class CortexSelectAvenue {file = "MissionScripts\AiScripting\Cortex\cortexSelectAvenue.sqf";};
            class CortexProfile {file = "MissionScripts\AiScripting\Cortex\cortexProfile.sqf";};
            class CortexStance {file = "MissionScripts\AiScripting\Cortex\cortexStance.sqf";};
            class CortexZeusHeld {file = "MissionScripts\AiScripting\Cortex\cortexZeusHeld.sqf";};
            class CortexZeusMark {file = "MissionScripts\AiScripting\Cortex\cortexZeusMark.sqf";};
            class CortexZeusWatchLocal {file = "MissionScripts\AiScripting\Cortex\cortexZeusWatchLocal.sqf";};
            // Legacy mission API aliases; production callers use Cortex names.
            class AIPassInit {file = "MissionScripts\AiScripting\Cortex\cortexInit.sqf";};
            class AIPassStop {file = "MissionScripts\AiScripting\Cortex\cortexStop.sqf";};
            class AIPassIsEligible {file = "MissionScripts\AiScripting\Cortex\cortexIsEligible.sqf";};
            class AIPassIsPaused {file = "MissionScripts\AiScripting\Cortex\cortexIsPaused.sqf";};
            class AIPassQueueJob {file = "MissionScripts\AiScripting\Cortex\cortexQueueJob.sqf";};
            class AIPassSchedulerTick {file = "MissionScripts\AiScripting\Cortex\cortexSchedulerTick.sqf";};
            class AIPassRegroupOnKill {file = "MissionScripts\AiScripting\Cortex\cortexRegroupOnKill.sqf";};
            class AIPassRegroupStep {file = "MissionScripts\AiScripting\Cortex\cortexRegroupStep.sqf";};
            class AIPassAirborneCheck {file = "MissionScripts\AiScripting\Cortex\cortexAirborneCheck.sqf";};
            class AIPassAirborneDropStep {file = "MissionScripts\AiScripting\Cortex\cortexAirborneDropStep.sqf";};
            class AIPassAirborneDrop {file = "MissionScripts\AiScripting\Cortex\cortexAirborneDrop.sqf";};
            class AIPassParachuteJump {file = "MissionScripts\AiScripting\Cortex\cortexParachuteJump.sqf";};
            class AIPassSettingsLocal {file = "MissionScripts\AiScripting\Cortex\cortexSettingsLocal.sqf";};
            class AIPassTuning {file = "MissionScripts\AiScripting\Cortex\cortexTuning.sqf";};
            class AIPassTuningSpec {file = "MissionScripts\AiScripting\Cortex\cortexTuningSpec.sqf";};
            class AIPassArtilleryRole {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryRole.sqf";};
            class AIPassSetArtilleryRole {file = "MissionScripts\AiScripting\Cortex\cortexSetArtilleryRole.sqf";};
            class AIPassReleaseFeatureCrew {file = "MissionScripts\AiScripting\Cortex\cortexReleaseFeatureCrew.sqf";};
            class AIPassAntiArmour {file = "MissionScripts\AiScripting\Cortex\cortexAntiArmour.sqf";};
            class AIPassCheckpoint {file = "MissionScripts\AiScripting\Cortex\cortexCheckpoint.sqf";};
            class AIPassLocality {file = "MissionScripts\AiScripting\Cortex\cortexLocality.sqf";};
            class AIPassSetSpotter {file = "MissionScripts\AiScripting\Cortex\cortexSetSpotter.sqf";};
            class AIPassSpotterFix {file = "MissionScripts\AiScripting\Cortex\cortexSpotterFix.sqf";};
            class AIPassArtilleryObserve {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryObserve.sqf";};
            class AIPassArtilleryReport {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryReport.sqf";};
            class AIPassArtilleryAim {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryAim.sqf";};
            class AIPassArtilleryAmmo {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryAmmo.sqf";};
            class AIPassArtilleryMissionStep {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryMissionStep.sqf";};
            class AIPassArtilleryShot {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryShot.sqf";};
            class AIPassArtilleryScoot {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryScoot.sqf";};
            class AIPassClearRelease {file = "MissionScripts\AiScripting\Cortex\cortexClearRelease.sqf";};
            class AIPassOrderDispatch {file = "MissionScripts\AiScripting\Cortex\cortexOrderDispatch.sqf";};
            class AIPassOrderLocal {file = "MissionScripts\AiScripting\Cortex\cortexOrderLocal.sqf";};
            class AIPassOrderResult {file = "MissionScripts\AiScripting\Cortex\cortexOrderResult.sqf";};
            class AIPassCounterObserve {file = "MissionScripts\AiScripting\Cortex\cortexCounterObserve.sqf";};
            class AIPassArtilleryFired {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryFired.sqf";};
            class AIPassArtilleryRejected {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryRejected.sqf";};
            class AIPassArtilleryFire {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryFire.sqf";};
            class AIPassArtilleryRequest {file = "MissionScripts\AiScripting\Cortex\cortexArtilleryRequest.sqf";};
            class AIPassCanTransmit {file = "MissionScripts\AiScripting\Cortex\cortexCanTransmit.sqf";};
            class AIPassClearBuilding {file = "MissionScripts\AiScripting\Cortex\cortexClearBuilding.sqf";};
            class AIPassReportServer {file = "MissionScripts\AiScripting\Cortex\cortexReportServer.sqf";};
            class AIPassReportLocal {file = "MissionScripts\AiScripting\Cortex\cortexReportLocal.sqf";};
            class AIPassHearingLocal {file = "MissionScripts\AiScripting\Cortex\cortexHearingLocal.sqf";};
            class AIPassContactReport {file = "MissionScripts\AiScripting\Cortex\cortexContactReport.sqf";};
            class AIPassCooldown {file = "MissionScripts\AiScripting\Cortex\cortexCooldown.sqf";};
            class AIPassCounterBattery {file = "MissionScripts\AiScripting\Cortex\cortexCounterBattery.sqf";};
            class AIPassDiscover {file = "MissionScripts\AiScripting\Cortex\cortexDiscover.sqf";};
            class AIPassFindCover {file = "MissionScripts\AiScripting\Cortex\cortexFindCover.sqf";};
            class AIPassFireControl {file = "MissionScripts\AiScripting\Cortex\cortexFireControl.sqf";};
            class AIPassFireCountermeasure {file = "MissionScripts\AiScripting\Cortex\cortexFireCountermeasure.sqf";};
            class AIPassFlankEnd {file = "MissionScripts\AiScripting\Cortex\cortexFlankEnd.sqf";};
            class AIPassFlankStart {file = "MissionScripts\AiScripting\Cortex\cortexFlankStart.sqf";};
            class AIPassFlankStep {file = "MissionScripts\AiScripting\Cortex\cortexFlankStep.sqf";};
            class AIPassGarrison {file = "MissionScripts\AiScripting\Cortex\cortexGarrison.sqf";};
            class AIPassGarrisonApplyLocal {file = "MissionScripts\AiScripting\Cortex\cortexGarrisonApplyLocal.sqf";};
            class AIPassGarrisonRelease {file = "MissionScripts\AiScripting\Cortex\cortexGarrisonRelease.sqf";};
            class AIPassGrenadeCheck {file = "MissionScripts\AiScripting\Cortex\cortexGrenadeCheck.sqf";};
            class AIPassGroupMove {file = "MissionScripts\AiScripting\Cortex\cortexGroupMove.sqf";};
            class AIPassGroupMoveClear {file = "MissionScripts\AiScripting\Cortex\cortexGroupMoveClear.sqf";};
            class AIPassGroupState {file = "MissionScripts\AiScripting\Cortex\cortexGroupState.sqf";};
            class AIPassGroupTick {file = "MissionScripts\AiScripting\Cortex\cortexGroupTick.sqf";};
            class AIPassKnowledge {file = "MissionScripts\AiScripting\Cortex\cortexKnowledge.sqf";};
            class AIPassLineOfFireClear {file = "MissionScripts\AiScripting\Cortex\cortexLineOfFireClear.sqf";};
            class AIPassMorale {file = "MissionScripts\AiScripting\Cortex\cortexMorale.sqf";};
            class AIPassRegisterRadar {file = "MissionScripts\AiScripting\Cortex\cortexRegisterRadar.sqf";};
            class AIPassSupportServer {file = "MissionScripts\AiScripting\Cortex\cortexSupportServer.sqf";};
            class AIPassSupportAssaultServer {file = "MissionScripts\AiScripting\Cortex\cortexSupportAssaultServer.sqf";};
            class AIPassSupportStep {file = "MissionScripts\AiScripting\Cortex\cortexSupportStep.sqf";};
            class AIPassSupportLocal {file = "MissionScripts\AiScripting\Cortex\cortexSupportLocal.sqf";};
            class AIPassSupportApply {file = "MissionScripts\AiScripting\Cortex\cortexSupportApply.sqf";};
            class AIPassSupportAck {file = "MissionScripts\AiScripting\Cortex\cortexSupportAck.sqf";};
            class AIPassSupportMaintain {file = "MissionScripts\AiScripting\Cortex\cortexSupportMaintain.sqf";};
            class AIPassReinforce {file = "MissionScripts\AiScripting\Cortex\cortexReinforce.sqf";};
            class AIPassReleaseGroup {file = "MissionScripts\AiScripting\Cortex\cortexReleaseGroup.sqf";};
            class AIPassRestoreCalm {file = "MissionScripts\AiScripting\Cortex\cortexRestoreCalm.sqf";};
            class AIPassRetreat {file = "MissionScripts\AiScripting\Cortex\cortexRetreat.sqf";};
            class AIPassSurrender {file = "MissionScripts\AiScripting\Cortex\cortexSurrender.sqf";};
            class AIPassThrowGrenade {file = "MissionScripts\AiScripting\Cortex\cortexThrowGrenade.sqf";};
            class AIPassFeatureEnabled {file = "MissionScripts\AiScripting\Cortex\cortexFeatureEnabled.sqf";};
            class AIPassCombatEffective {file = "MissionScripts\AiScripting\Cortex\cortexCombatEffective.sqf";};
            class AIPassCapabilities {file = "MissionScripts\AiScripting\Cortex\cortexCapabilities.sqf";};
            class AIPassPassengerReady {file = "MissionScripts\AiScripting\Cortex\cortexPassengerReady.sqf";};
            class AIPassInfantrySpeed {file = "MissionScripts\AiScripting\Cortex\cortexInfantrySpeed.sqf";};
            class AIPassUnitRole {file = "MissionScripts\AiScripting\Cortex\cortexUnitRole.sqf";};
            class AIPassVehicles {file = "MissionScripts\AiScripting\Cortex\cortexVehicles.sqf";};
            class AIPassTacticalStart {file = "MissionScripts\AiScripting\Cortex\cortexTacticalStart.sqf";};
            class AIPassAdvanceStart {file = "MissionScripts\AiScripting\Cortex\cortexAdvanceStart.sqf";};
            class AIPassAmmoShare {file = "MissionScripts\AiScripting\Cortex\cortexAmmoShare.sqf";};
            class AIPassCoordinatedAssault {file = "MissionScripts\AiScripting\Cortex\cortexCoordinatedAssault.sqf";};
            class AIPassDefend {file = "MissionScripts\AiScripting\Cortex\cortexDefend.sqf";};
            class AIPassDefendApplyLocal {file = "MissionScripts\AiScripting\Cortex\cortexDefendApplyLocal.sqf";};
            class AIPassDefendRelease {file = "MissionScripts\AiScripting\Cortex\cortexDefendRelease.sqf";};
            class AIPassDefendStep {file = "MissionScripts\AiScripting\Cortex\cortexDefendStep.sqf";};
            class AIPassPlanRoute {file = "MissionScripts\AiScripting\Cortex\cortexPlanRoute.sqf";};
            class AIPassProfile {file = "MissionScripts\AiScripting\Cortex\cortexProfile.sqf";};
            class AIPassStance {file = "MissionScripts\AiScripting\Cortex\cortexStance.sqf";};
            class AIPassZeusHeld {file = "MissionScripts\AiScripting\Cortex\cortexZeusHeld.sqf";};
            class AIPassZeusMark {file = "MissionScripts\AiScripting\Cortex\cortexZeusMark.sqf";};
            class AIPassZeusWatchLocal {file = "MissionScripts\AiScripting\Cortex\cortexZeusWatchLocal.sqf";};

            class ImprovedHelicopterLandingInit {file = "MissionScripts\AiScripting\improvedHelicopterLandingInit.sqf";};
            class ImprovedHelicopterLandingTrackLocal {file = "MissionScripts\AiScripting\improvedHelicopterLandingTrackLocal.sqf";};
            class ImprovedHelicopterLandingExecuteLocal {file = "MissionScripts\AiScripting\improvedHelicopterLandingExecuteLocal.sqf";};
            class ImprovedHelicopterLandingAnchorLocal {file = "MissionScripts\AiScripting\improvedHelicopterLandingAnchorLocal.sqf";};
            class ImprovedHelicopterLandingRestoreLocal {file = "MissionScripts\AiScripting\improvedHelicopterLandingRestoreLocal.sqf";};
            class ImprovedHelicopterLandingSetting {file = "MissionScripts\AiScripting\improvedHelicopterLandingSetting.sqf";};
            class ImprovedHelicopterLandingConfigureServer {file = "MissionScripts\AiScripting\improvedHelicopterLandingConfigureServer.sqf";};
            class HelicopterDecelerationInit {file = "MissionScripts\AiScripting\helicopterDecelerationInit.sqf";};
            class HelicopterDecelerationTrackLocal {file = "MissionScripts\AiScripting\helicopterDecelerationTrackLocal.sqf";};
            class HelicopterDecelerationCorrectLocal {file = "MissionScripts\AiScripting\helicopterDecelerationCorrectLocal.sqf";};
        };
    };
};
