/*
 * Author: WaldoTheWarfighter
 * Registers the standalone Waldos AI Tweaks mission functions.
 * Locality / Authority: Compilation is local; each function documents its own execution authority.
 * Repeat/JIP: CfgFunctions compilation is repeat-safe and available to joining machines.
 * Arguments: None.
 * Return Value: CfgFunctions declaration.
 * Current callers: include from the addon config.cpp.
 * Example: #include "CfgFunctions.hpp"
 */
class CfgFunctions {
    class Waldo {
        class AI
        {
            class AITweaksNotifyLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\aiTweaksNotifyLocal.sqf";};
            class AITweaksDiagnosticReport {file = "\z\waldo_ai_tweaks\addons\main\functions\aiTweaksDiagnosticReport.sqf";};
            class AITweaksDetectCompatibility {file = "\z\waldo_ai_tweaks\addons\main\functions\aiTweaksDetectCompatibility.sqf";};
            class AITweaksRegisterSettings {file = "\z\waldo_ai_tweaks\addons\main\functions\aiTweaksRegisterSettings.sqf";};
            class AITweaksSettingChanged {file = "\z\waldo_ai_tweaks\addons\main\functions\aiTweaksSettingChanged.sqf";};
            class AITweaksSettingsRequestServer {file = "\z\waldo_ai_tweaks\addons\main\functions\aiTweaksSettingsRequestServer.sqf";};
            class AITweaksUiTheme {file = "\z\waldo_ai_tweaks\addons\main\functions\aiTweaksUiTheme.sqf";};
            class HeadlessResolveSender {file = "\z\waldo_ai_tweaks\addons\main\functions\headlessResolveSender.sqf";};
            class ConvoyThreat {file = "\z\waldo_ai_tweaks\addons\main\functions\convoyThreat.sqf";};
            class ConvoyDismountLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\convoyDismountLocal.sqf";};
            class ConvoyHaltServer {file = "\z\waldo_ai_tweaks\addons\main\functions\convoyHaltServer.sqf";};
            class ConvoyCrewLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\convoyCrewLocal.sqf";};
            class ConvoySync {file = "\z\waldo_ai_tweaks\addons\main\functions\convoySync.sqf";};
            class ConvoyReleaseLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\convoyReleaseLocal.sqf";};
            class ConvoyTick {file = "\z\waldo_ai_tweaks\addons\main\functions\convoyTick.sqf";};
            class ZenConvoyModule {file = "\z\waldo_ai_tweaks\addons\main\functions\zenConvoyModule.sqf";};
            class SimpleAiConvoy {
                file =  "\z\waldo_ai_tweaks\addons\main\functions\simpleAiConvoy.sqf";
            };
            class AITweak {
                file = "\z\waldo_ai_tweaks\addons\main\functions\AISkillAdjustmentSystem.sqf";
            };
            class AIRebalanceInit {
                file = "\z\waldo_ai_tweaks\addons\main\functions\aiRebalanceInit.sqf";
            };
            class AIHeadlessAdoptionResultServer {
                file = "\z\waldo_ai_tweaks\addons\main\functions\aiHeadlessAdoptionResultServer.sqf";
            };
            class AIGetDiagnostics {
                file = "\z\waldo_ai_tweaks\addons\main\functions\aiGetDiagnostics.sqf";
            };
            class AIApplyProfile {
                file = "\z\waldo_ai_tweaks\addons\main\functions\aiApplyProfile.sqf";
            };
            class AIRebalanceStop {
                file = "\z\waldo_ai_tweaks\addons\main\functions\aiRebalanceStop.sqf";
            };
            class CortexInit {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexInit.sqf";};
            class CortexStop {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexStop.sqf";};
            class CortexIsEligible {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexIsEligible.sqf";};
            class CortexExternalOwner {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexExternalOwner.sqf";};
            class CortexCivilianReact {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCivilianReact.sqf";};
            class CortexCivilianSetup {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCivilianSetup.sqf";};
            class CortexIsPaused {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexIsPaused.sqf";};
            class CortexQueueJob {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexQueueJob.sqf";};
            class CortexSchedulerTick {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSchedulerTick.sqf";};
            class CortexRegroupOnKill {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexRegroupOnKill.sqf";};
            class CortexRegroupStep {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexRegroupStep.sqf";};
            class CortexAirborneCheck {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAirborneCheck.sqf";};
            class CortexAirborneDropStep {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAirborneDropStep.sqf";};
            class CortexAirborneDrop {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAirborneDrop.sqf";};
            class CortexParachuteJump {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexParachuteJump.sqf";};
            class CortexSettingsLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSettingsLocal.sqf";};
            class CortexTuning {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexTuning.sqf";};
            class CortexOrderReason {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexOrderReason.sqf";};
            class CortexControlOpenLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexControlOpenLocal.sqf";};
            class CortexControlPageLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexControlPageLocal.sqf";};
            class CortexTuningSpec {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexTuningSpec.sqf";};
            class CortexArtilleryRole {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryRole.sqf";};
            class CortexSetArtilleryRole {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSetArtilleryRole.sqf";};
            class CortexOwnershipLease {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexOwnershipLease.sqf";};
            class CortexBuildingBackendStart {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexBuildingBackendStart.sqf";};
            class CortexBuildingBackendRelease {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexBuildingBackendRelease.sqf";};
            class CortexAntiArmour {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAntiArmour.sqf";};
            class CortexCheckpoint {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCheckpoint.sqf";};
            class CortexLocality {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexLocality.sqf";};
            class CortexSetSpotter {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSetSpotter.sqf";};
            class CortexSpotterFix {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSpotterFix.sqf";};
            class CortexArtilleryObserve {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryObserve.sqf";};
            class CortexArtilleryReport {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryReport.sqf";};
            class CortexArtilleryAim {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryAim.sqf";};
            class CortexArtilleryAmmo {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryAmmo.sqf";};
            class CortexArtilleryMissionStep {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryMissionStep.sqf";};
            class CortexArtilleryShot {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryShot.sqf";};
            class CortexArtilleryScoot {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryScoot.sqf";};
            class CortexClearRelease {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexClearRelease.sqf";};
            class CortexOrderDispatch {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexOrderDispatch.sqf";};
            class CortexOrderLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexOrderLocal.sqf";};
            class CortexOrderResult {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexOrderResult.sqf";};
            class CortexCounterObserve {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCounterObserve.sqf";};
            class CortexArtilleryFired {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryFired.sqf";};
            class CortexArtilleryRejected {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryRejected.sqf";};
            class CortexArtilleryFire {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryFire.sqf";};
            class CortexArtilleryRequest {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryRequest.sqf";};
            class CortexCanTransmit {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCanTransmit.sqf";};
            class CortexBuildingDoor {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexBuildingDoor.sqf";};
            class CortexClearBuilding {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexClearBuilding.sqf";};
            class CortexReportServer {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexReportServer.sqf";};
            class CortexReportLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexReportLocal.sqf";};
            class CortexHearingLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexHearingLocal.sqf";};
            class CortexContactReport {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexContactReport.sqf";};
            class CortexCombinedArmsRequest {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCombinedArmsRequest.sqf";};
            class CortexCombinedArmsServer {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCombinedArmsServer.sqf";};
            class CortexCombinedArmsLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCombinedArmsLocal.sqf";};
            class CortexCombinedGroundStep {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCombinedGroundStep.sqf";};
            class CortexCooldown {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCooldown.sqf";};
            class CortexCounterBattery {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCounterBattery.sqf";};
            class CortexAttackRunFlares {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAttackRunFlares.sqf";};
            class CortexAirAttackPlan {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAirAttackPlan.sqf";};
            class CortexAirAttack {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAirAttack.sqf";};
            class CortexAirHandoverRestoreLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAirHandoverRestoreLocal.sqf";};
            class CortexAircraftEligible {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAircraftEligible.sqf";};
            class CortexDiscover {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexDiscover.sqf";};
            class CortexFindCover {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexFindCover.sqf";};
            class CortexFireControl {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexFireControl.sqf";};
            class CortexFireCountermeasure {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexFireCountermeasure.sqf";};
            class CortexFlankEnd {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexFlankEnd.sqf";};
            class CortexFlankStart {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexFlankStart.sqf";};
            class CortexFlankStep {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexFlankStep.sqf";};
            class CortexDrillStart {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexDrillStart.sqf";};
            class CortexDrillSetStage {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexDrillSetStage.sqf";};
            class CortexSetPhase {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSetPhase.sqf";};
            class CortexGarrison {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGarrison.sqf";};
            class CortexGarrisonApplyLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGarrisonApplyLocal.sqf";};
            class CortexGarrisonRelease {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGarrisonRelease.sqf";};
            class CortexGrenadeCheck {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGrenadeCheck.sqf";};
            class CortexGroupMove {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGroupMove.sqf";};
            class CortexGroupMoveClear {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGroupMoveClear.sqf";};
            class CortexGroupState {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGroupState.sqf";};
            class CortexGroupTick {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGroupTick.sqf";};
            class CortexKnowledge {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexKnowledge.sqf";};
            class CortexLineOfFireClear {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexLineOfFireClear.sqf";};
            class CortexMorale {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexMorale.sqf";};
            class CortexRegisterRadar {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexRegisterRadar.sqf";};
            class CortexSupportServer {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportServer.sqf";};
            class CortexSupportAssaultServer {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportAssaultServer.sqf";};
            class CortexSupportStep {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportStep.sqf";};
            class CortexSupportLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportLocal.sqf";};
            class CortexSupportApply {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportApply.sqf";};
            class CortexSupportAck {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportAck.sqf";};
            class CortexSupportMaintain {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportMaintain.sqf";};
            class CortexSupportCoordinateStep {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportCoordinateStep.sqf";};
            class CortexSupportBoundStart {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportBoundStart.sqf";};
            class CortexReinforce {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexReinforce.sqf";};
            class CortexReleaseGroup {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexReleaseGroup.sqf";};
            class CortexRestoreCalm {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexRestoreCalm.sqf";};
            class CortexRetreat {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexRetreat.sqf";};
            class CortexSurrender {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSurrender.sqf";};
            class CortexThrowGrenade {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexThrowGrenade.sqf";};
            class CortexFeatureEnabled {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexFeatureEnabled.sqf";};
            class CortexCombatEffective {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCombatEffective.sqf";};
            class CortexCapabilities {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCapabilities.sqf";};
            class CortexPassengerReady {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexPassengerReady.sqf";};
            class CortexInfantrySpeed {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexInfantrySpeed.sqf";};
            class CortexUnitRole {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexUnitRole.sqf";};
            class CortexOnboardContact {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexOnboardContact.sqf";};
            class CortexVehicles {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexVehicles.sqf";};
            class CortexNavalAssault {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexNavalAssault.sqf";};
            class CortexNavalRelease {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexNavalRelease.sqf";};
            class CortexTacticalStart {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexTacticalStart.sqf";};
            class CortexAdvanceStart {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAdvanceStart.sqf";};
            class CortexAmmoShare {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAmmoShare.sqf";};
            class CortexCoordinatedAssault {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCoordinatedAssault.sqf";};
            class CortexDefend {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexDefend.sqf";};
            class CortexDefendApplyLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexDefendApplyLocal.sqf";};
            class CortexDefendRelease {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexDefendRelease.sqf";};
            class CortexDefendStep {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexDefendStep.sqf";};
            class CortexPlanRoute {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexPlanRoute.sqf";};
            class CortexSelectAvenue {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSelectAvenue.sqf";};
            class CortexProfile {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexProfile.sqf";};
            class CortexStance {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexStance.sqf";};
            class CortexZeusHeld {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexZeusHeld.sqf";};
            class CortexZeusMark {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexZeusMark.sqf";};
            class CortexZeusWatchLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexZeusWatchLocal.sqf";};
            // Legacy mission API aliases; production callers use Cortex names.
            class AIPassInit {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexInit.sqf";};
            class AIPassStop {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexStop.sqf";};
            class AIPassIsEligible {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexIsEligible.sqf";};
            class AIPassIsPaused {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexIsPaused.sqf";};
            class AIPassQueueJob {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexQueueJob.sqf";};
            class AIPassSchedulerTick {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSchedulerTick.sqf";};
            class AIPassRegroupOnKill {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexRegroupOnKill.sqf";};
            class AIPassRegroupStep {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexRegroupStep.sqf";};
            class AIPassAirborneCheck {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAirborneCheck.sqf";};
            class AIPassAirborneDropStep {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAirborneDropStep.sqf";};
            class AIPassAirborneDrop {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAirborneDrop.sqf";};
            class AIPassParachuteJump {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexParachuteJump.sqf";};
            class AIPassSettingsLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSettingsLocal.sqf";};
            class AIPassTuning {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexTuning.sqf";};
            class AIPassTuningSpec {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexTuningSpec.sqf";};
            class AIPassArtilleryRole {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryRole.sqf";};
            class AIPassSetArtilleryRole {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSetArtilleryRole.sqf";};
            class AIPassAntiArmour {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAntiArmour.sqf";};
            class AIPassCheckpoint {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCheckpoint.sqf";};
            class AIPassLocality {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexLocality.sqf";};
            class AIPassSetSpotter {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSetSpotter.sqf";};
            class AIPassSpotterFix {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSpotterFix.sqf";};
            class AIPassArtilleryObserve {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryObserve.sqf";};
            class AIPassArtilleryReport {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryReport.sqf";};
            class AIPassArtilleryAim {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryAim.sqf";};
            class AIPassArtilleryAmmo {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryAmmo.sqf";};
            class AIPassArtilleryMissionStep {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryMissionStep.sqf";};
            class AIPassArtilleryShot {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryShot.sqf";};
            class AIPassArtilleryScoot {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryScoot.sqf";};
            class AIPassClearRelease {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexClearRelease.sqf";};
            class AIPassOrderDispatch {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexOrderDispatch.sqf";};
            class AIPassOrderLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexOrderLocal.sqf";};
            class AIPassOrderResult {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexOrderResult.sqf";};
            class AIPassCounterObserve {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCounterObserve.sqf";};
            class AIPassArtilleryFired {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryFired.sqf";};
            class AIPassArtilleryRejected {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryRejected.sqf";};
            class AIPassArtilleryFire {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryFire.sqf";};
            class AIPassArtilleryRequest {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexArtilleryRequest.sqf";};
            class AIPassCanTransmit {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCanTransmit.sqf";};
            class AIPassClearBuilding {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexClearBuilding.sqf";};
            class AIPassReportServer {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexReportServer.sqf";};
            class AIPassReportLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexReportLocal.sqf";};
            class AIPassHearingLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexHearingLocal.sqf";};
            class AIPassContactReport {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexContactReport.sqf";};
            class AIPassCooldown {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCooldown.sqf";};
            class AIPassCounterBattery {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCounterBattery.sqf";};
            class AIPassDiscover {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexDiscover.sqf";};
            class AIPassFindCover {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexFindCover.sqf";};
            class AIPassFireControl {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexFireControl.sqf";};
            class AIPassFireCountermeasure {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexFireCountermeasure.sqf";};
            class AIPassFlankEnd {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexFlankEnd.sqf";};
            class AIPassFlankStart {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexFlankStart.sqf";};
            class AIPassFlankStep {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexFlankStep.sqf";};
            class AIPassGarrison {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGarrison.sqf";};
            class AIPassGarrisonApplyLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGarrisonApplyLocal.sqf";};
            class AIPassGarrisonRelease {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGarrisonRelease.sqf";};
            class AIPassGrenadeCheck {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGrenadeCheck.sqf";};
            class AIPassGroupMove {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGroupMove.sqf";};
            class AIPassGroupMoveClear {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGroupMoveClear.sqf";};
            class AIPassGroupState {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGroupState.sqf";};
            class AIPassGroupTick {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexGroupTick.sqf";};
            class AIPassKnowledge {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexKnowledge.sqf";};
            class AIPassLineOfFireClear {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexLineOfFireClear.sqf";};
            class AIPassMorale {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexMorale.sqf";};
            class AIPassRegisterRadar {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexRegisterRadar.sqf";};
            class AIPassSupportServer {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportServer.sqf";};
            class AIPassSupportAssaultServer {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportAssaultServer.sqf";};
            class AIPassSupportStep {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportStep.sqf";};
            class AIPassSupportLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportLocal.sqf";};
            class AIPassSupportApply {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportApply.sqf";};
            class AIPassSupportAck {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportAck.sqf";};
            class AIPassSupportMaintain {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSupportMaintain.sqf";};
            class AIPassReinforce {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexReinforce.sqf";};
            class AIPassReleaseGroup {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexReleaseGroup.sqf";};
            class AIPassRestoreCalm {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexRestoreCalm.sqf";};
            class AIPassRetreat {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexRetreat.sqf";};
            class AIPassSurrender {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexSurrender.sqf";};
            class AIPassThrowGrenade {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexThrowGrenade.sqf";};
            class AIPassFeatureEnabled {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexFeatureEnabled.sqf";};
            class AIPassCombatEffective {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCombatEffective.sqf";};
            class AIPassCapabilities {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCapabilities.sqf";};
            class AIPassPassengerReady {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexPassengerReady.sqf";};
            class AIPassInfantrySpeed {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexInfantrySpeed.sqf";};
            class AIPassUnitRole {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexUnitRole.sqf";};
            class AIPassVehicles {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexVehicles.sqf";};
            class AIPassTacticalStart {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexTacticalStart.sqf";};
            class AIPassAdvanceStart {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAdvanceStart.sqf";};
            class AIPassAmmoShare {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexAmmoShare.sqf";};
            class AIPassCoordinatedAssault {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexCoordinatedAssault.sqf";};
            class AIPassDefend {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexDefend.sqf";};
            class AIPassDefendApplyLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexDefendApplyLocal.sqf";};
            class AIPassDefendRelease {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexDefendRelease.sqf";};
            class AIPassDefendStep {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexDefendStep.sqf";};
            class AIPassPlanRoute {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexPlanRoute.sqf";};
            class AIPassProfile {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexProfile.sqf";};
            class AIPassStance {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexStance.sqf";};
            class AIPassZeusHeld {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexZeusHeld.sqf";};
            class AIPassZeusMark {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexZeusMark.sqf";};
            class AIPassZeusWatchLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\Cortex\cortexZeusWatchLocal.sqf";};

            class ImprovedHelicopterLandingInit {file = "\z\waldo_ai_tweaks\addons\main\functions\improvedHelicopterLandingInit.sqf";};
            class ImprovedHelicopterLandingTrackLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\improvedHelicopterLandingTrackLocal.sqf";};
            class ImprovedHelicopterLandingExecuteLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\improvedHelicopterLandingExecuteLocal.sqf";};
            class ImprovedHelicopterLandingAnchorLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\improvedHelicopterLandingAnchorLocal.sqf";};
            class ImprovedHelicopterLandingRestoreLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\improvedHelicopterLandingRestoreLocal.sqf";};
            class ImprovedHelicopterLandingSetting {file = "\z\waldo_ai_tweaks\addons\main\functions\improvedHelicopterLandingSetting.sqf";};
            class ImprovedHelicopterLandingConfigureServer {file = "\z\waldo_ai_tweaks\addons\main\functions\improvedHelicopterLandingConfigureServer.sqf";};
            class HelicopterDecelerationInit {file = "\z\waldo_ai_tweaks\addons\main\functions\helicopterDecelerationInit.sqf";};
            class HelicopterDecelerationTrackLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\helicopterDecelerationTrackLocal.sqf";};
            class HelicopterDecelerationCorrectLocal {file = "\z\waldo_ai_tweaks\addons\main\functions\helicopterDecelerationCorrectLocal.sqf";};
        };
    };
};
