name = "Waldos AI Tweaks"
prefix = "waldo_ai_tweaks"
mainprefix = "z"

[version]
major = 0
minor = 1
patch = 0
git_hash = 0

[files]
include = ["README.md", "LICENSE", "docs/MODDING-AND-OPERATIONS.md"]

[properties]
author = "WaldoTheWarfighter"
url = "https://github.com/AdamWaldie/WaldosAITweaks"
